#!/usr/bin/env php
<?php

use Tendo\Tendo;

if (version_compare('5.4.0', PHP_VERSION, '>')) {
    echo 'Your version of PHP is outdated.' . PHP_EOL;
    die(1);
}

if (!ini_get('date.timezone')) {
    ini_set('date.timezone', 'UTC');
}

if (!is_readable('vendor/autoload.php')) {
    echo 'Composer dependecies not installed, please run "composer install".' . PHP_EOL;
}

require 'vendor/autoload.php';

if (count($argv) > 0) {
    array_shift($argv);
    $filenames = $argv;
}

$test = new Tendo();
foreach ($filenames as $filename) {
    if (is_readable($filename)) {
        echo '> ' . $filename . PHP_EOL;
        require 'exempleCLI.php';
        echo PHP_EOL;
    }
}
$test->results();
